theme: jekyll-theme-cayman
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
collections:
  tools:
    output: true
    permalink: /:collection/:name
defaults:
 - scope:
     path: ""
   values:
     layout: "default"
 - scope:
     path: ""
     type: "tools"
   values:
     layout: "tools"
