theme: jekyll-theme-cayman
collections:
  tools:
    output: true
    permalink: /:collection/:name
defaults:
 - scope:
     path: ""
   values:
     layout: "default"
 - scope:
     path: ""
     type: "tools"
   values:
     layout: "tools"
